This DBUtils java class contains the DB related code...
This line updating now for change in logic...
Updated this line after modified depploy.sh in remote repo for testing wether the changes applied or not from local repo to remote repo while doing push action...
